name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
        id: setup-go

      - name: check out code
        uses: actions/checkout@v3
        id: checkout

      - name: Get dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run tests
        run: |
          make test
