name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
        id: setup-go

      - name: check out code
        uses: actions/checkout@v3
        id: checkout

      - name: Install golang-migrate
        run: |
          go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Install sqlc
        run: |
          go install github.com/kyleconroy/sqlc/cmd/sqlc@latest

      - name: migrate up
        run: |
          make migrateup

      - name: Get dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run tests
        run: |
          make test
